name: docker publish

on:
  push:
    branches:
      - "feature/**"
      - "release/**"
      - "develop"
      - "master"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Login to DockerHub Registry
        run: echo ${{ secrets.dockerhub_token }} | docker login -u ${{ secrets.dockerhub_username }} --password-stdin
      - name: Get the version
        id: vars
        run: echo ::set-output name=tag::$(echo ${GITHUB_REF:10})
      - name: Print the version
        run: echo ${{steps.vars.outputs.tag}}
      - name: Build the latest Docker image
        run: docker build . --file Dockerfile --tag lanceschi/helix-editor-musl:latest
      - name: Push the latest Docker image
        run: docker push lanceschi/helix-editor-musl:latest